[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
 
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/_api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
